name: Publish

on:
  push:
    tags:
      - '**'
      - '!**-alpha'
env:
  IMAGE_NAME: jellyfin

jobs:
  push-ghcr:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        platform: [linux/amd64, linux/arm/v7, linux/arm64]
        include:
          - platform: linux/amd64
            file: ./Dockerfile
          - platform: linux/arm/v7
            file: ./Dockerfile.arm
          - platform: linux/arm64
            file: ./Dockerfile.arm64
    env:
      TZ: Asia/Shanghai
      REGISTRY: ghcr.io
    steps:
      - uses: actions/checkout@v2

      - name: Set output
        id: set-output-id
        run: |
          VERSION=edge
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            VERSION=${GITHUB_REF#refs/tags/v}
          fi
          echo "tags=${VERSION}" >> $GITHUB_OUTPUT

      - name: Login
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build && Push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ${{ matrix.file }}
          platforms: ${{ matrix.platform }}
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:${{ steps.set-output-id.outputs.tags }}
            ${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:latest

  push-dockerhub:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        platform: [linux/amd64, linux/arm/v7, linux/arm64]
        include:
          - platform: linux/amd64
            file: ./Dockerfile
          - platform: linux/arm/v7
            file: ./Dockerfile.arm
          - platform: linux/arm64
            file: ./Dockerfile.arm64
    env:
      TZ: Asia/Shanghai
      REGISTRY: docker.io
    steps:
      - uses: actions/checkout@v2

      - name: Set output
        id: set-output-id
        run: |
          VERSION=edge
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            VERSION=${GITHUB_REF#refs/tags/v}
          fi
          echo "tags=${VERSION}" >> $GITHUB_OUTPUT

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ${{ matrix.file }}
          platforms: ${{ matrix.platform }}
          push: true
          tags: |
            ${{ env.REGISTRY }}/azhi/${{ env.IMAGE_NAME }}:${{ steps.set-output-id.outputs.tags }}
            ${{ env.REGISTRY }}/azhi/${{ env.IMAGE_NAME }}:latest
